{"uuid":"575836d7-447f-443d-86bf-da2720948618","historyId":"80414f406fb501010715b3706d393ccb","fullName":"automationexercise.tests.HomeTest.localizarAgenciaPorCepInvalidoSemSucesso","labels":[{"name":"package","value":"automationexercise.tests.HomeTest"},{"name":"testClass","value":"automationexercise.tests.HomeTest"},{"name":"testMethod","value":"localizarAgenciaPorCepInvalidoSemSucesso"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"ProjetoSiteSicredi"},{"name":"subSuite","value":"automationexercise.tests.HomeTest"},{"name":"host","value":"DESKTOP-68FIEUE"},{"name":"thread","value":"17856@DESKTOP-68FIEUE.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"feature","value":"Localizar Agência"},{"name":"epic","value":"Site Sicredi"},{"name":"severity","value":"minor"}],"links":[],"name":"localizarAgenciaPorCepInvalidoSemSucesso","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"did not expect to find [] but found []","trace":"java.lang.AssertionError: did not expect to find [] but found []\r\n\tat org.testng.Assert.fail(Assert.java:97)\r\n\tat org.testng.Assert.assertNotEquals(Assert.java:1401)\r\n\tat org.testng.Assert.assertNotEquals(Assert.java:1406)\r\n\tat automationexercise.tests.HomeTest.localizarAgenciaPorCepInvalidoSemSucesso(HomeTest.java:86)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)\r\n\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)\r\n\tat org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)\r\n\tat org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:770)\r\n\tat org.testng.TestRunner.run(TestRunner.java:591)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:402)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:304)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1102)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1032)\r\n\tat org.testng.TestNG.run(TestNG.java:1000)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)\r\n"},"stage":"finished","description":"Validar navegar pesquisar agência por Cep inválido","steps":[],"attachments":[],"parameters":[],"start":1695932962506,"stop":1695932965859}